### PR TITLE
Prometheus setup and instructions.

### PR DESCRIPTION
**Pull request by shaliko**
Related to https://github.com/apinf/api-umbrella-dashboard/issues/1028

### CODE REVIEW

**Comment by jykae** [comment]
@shaliko Reviewing

**Comment by jykae** [comment]
Got setup up & running on local docker-machine on my Mac. @shaliko Thanks for some additional help regarding testing on localhost.

Some configuration problems with SMTP, trying to alert, but email sending fails:

```
alertmanager_1   | time="2016-06-22T14:56:21Z" level=warning msg="Notify attempt 13 failed: sending mail from: 530 5.7.0 Must issue a STARTTLS command first. 16sm58078ljj.47 - gsmtp" source="notify.go:193"
```

Could you add Grafana templates you have to simplify adding new node charts?

Great work with this.

**Comment by shaliko** [comment]
@jykae Yep, will update pull request today at evening.

**Comment by shaliko** [comment]
@jykae Thanks for review!

**Comment by jykae** [comment]
@shaliko Found PR related to SMTP issue, https://github.com/prometheus/alertmanager/pull/266 I suppose we have that new version that has the fix? Included here https://github.com/prometheus/alertmanager/releases/tag/0.2.0

EDIT: We use version 0.1.1, let's try to increase it to 0.2.0

**Comment by shaliko** [comment]
@jykae Yes, we use 0.1.1 because it was last version on date when I prepared monitoring configuration.

Thanks for catch new version, will try upgrade.

**Comment by shaliko** [comment]
@jykae 
- Updated 'alertmanager' to version "0.2.1" and changed 'alertmanager/alertmanager.yml.example'
- Added 'grafana/charts_template.json' as example of Grafana dashboard.

**Comment by jykae** [comment]
@shaliko 🆒 I take a look

**Comment by jykae** [comment]
Still getting the same email error when alert triggers and tries to send email.. :/ @shaliko Did you get the alert emails working?

**Comment by jykae** [comment]
@shaliko Got alert emails working when tried on testing server and not on my Macbook (localhost).

**Comment by jykae** [comment]
I think this is ok now, merging. Good work.

**Comment by shaliko** [comment]
@jykae Sorry for delay, yes works OK email sending locally and on production.

**Pull request merged**
